# Example workflow for manual forgepush.
# set secret "forgetoken" to your CurseForge API token
# this will publish using the package.yaml and latest version of forgepush

name: publish

on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      # Runs a single command using the runners shell
      - name: Publish
        run: |
          cd $GITHUB_WORKSPACE
          wget https://raw.githubusercontent.com/tmg-pub/forgepush/main/forgepush.py -O ../forgepush.py
          python3 ../forgepush.py --yesokay --curse_apitoken ${{secrets.FORGETOKEN}} --publish_curseforge --github_token ${{secrets.GITHUB_TOKEN}} --create_github_release --addonversion ${{github.ref_name}} --github_repo $GITHUB_REPOSITORY
